### ISSUE TITLE
运行demo报错，cuDnn error:CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by Dyt5358** [zju3dv/snake#182]
![d9e25d3f2d0acb239f2d6075c20e2d2](https://user-images.githubusercontent.com/74446581/124693994-03705c00-df13-11eb-93ae-3a47d33fdbb9.png)
![beae953ddb37ac92581e15b16f6eebf](https://user-images.githubusercontent.com/74446581/124693998-066b4c80-df13-11eb-9cbe-41da58f02e8a.png)
显卡：3080
cuda10.2
cudnn7.6.5
安装包情况：
![10f067d27207511d27058c7ebd856e8](https://user-images.githubusercontent.com/74446581/124695378-a88c3400-df15-11eb-91c2-194bd63b62c7.png)
![aaa29dfcd13ed2012420ed565bfed6a](https://user-images.githubusercontent.com/74446581/124695383-aaee8e00-df15-11eb-8424-d654f81e31a6.png)

- 有说改batch_size和图片大小的。我改了sbd_snake.yaml里的batch_size 80->40
- 有说可能是模型没有放到cuda上，只是把输出放到cuda了。我看了作者demo里是用的network = make_network(cfg).cuda().应该也是没问题的。

自己找不到什么好的解决办法，小白问下作者大大 有碰到这个情况吗？。。。

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/issues/142

**Comment by Dyt5358** [comment]
作者我的问题已经解决了问题找到了。首先是我用的3080显卡应该只支持cuda11以上版本，而我傻乎乎用的cuda10.2，掉用的时候就报错。后来我换了cuda11。然后dcn_v2无法编译。搜了一圈找到dcn_v2论文更新的dcn_v2,替换了作者原论文中的包，然后就可以编译dcn_v2了。现在可以运行demo了。现在的环境用的torc1.8.1,cuda11.1也可用dcn_v2。
