### ISSUE TITLE
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:51

### ISSUE THREAD

**Issue by wangshuo2020** [zju3dv/snake#94]
~~~
(snake) ws@ws-OMEN-Laptop-15-ek0xxx:~/snake$ python run.py --type demo --cfg_file configs/sbd_snake.yaml demo_path demo_images/2009_000871.jpg ct_score 0.3
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=51 error=30 : unknown error
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 95, in run_demo
    demo.demo()
  File "/home/ws/snake/tools/demo.py", line 59, in demo
    network = make_network(cfg).cuda()
  File "/home/ws/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/ws/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/ws/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/ws/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/ws/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/home/ws/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/ws/anaconda3/envs/snake/lib/python3.7/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:51

**Comment by wangshuo2020** [comment]
我安装的环境是cuda9.0 pytorch1.1.0 gcc5.5 在执行示例程序的时候报了这个错 查了资料还是说可能是版本的问题 这个版本搭配应该没什么问题吧

**Comment by pengsida** [comment]
我没遇到你这个问题。
你说的环境应该没问题，但不确定你有没有装对。
你这个报错看起来好像是无法执行pytorch代码，和我的代码关系不大。

**Comment by wangshuo2020** [comment]
> 我没遇到你这个问题。
> 你说的环境应该没问题，但不确定你有没有装对。
> 你这个报错看起来好像是无法执行pytorch代码，和我的代码关系不大。

显卡驱动在安装的时候使用gcc-7来编译的 现在用gcc-5来执行是不是出现问题的原因呢

**Comment by wangshuo2020** [comment]
重装显卡驱动后的报错
~~~
(snake_v2) ws@ws-OMEN-Laptop-15-ek0xxx:~/snake$ python run.py --type demo --cfg_file configs/sbd_snake.yaml demo_path demo_images/2009_000871.jpg ct_score 0.3
load model: data/model/snake/sbd/149.pth
  0%|                                                     | 0/1 [00:00<?, ?it/s]THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 95, in run_demo
    demo.demo()
  File "/home/ws/snake/tools/demo.py", line 68, in demo
    output = network(batch['inp'], batch)
  File "/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/ct_snake.py", line 54, in forward
    output, cnn_feature = self.dla(x)
  File "/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 470, in forward
    x = self.dla_up(x)
  File "/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 409, in forward
    ida(layers, len(layers) - i - 2, len(layers))
  File "/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 383, in forward
    layers[i] = upsample(project(layers[i]))
  File "/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 356, in forward
    x = self.conv(x)
  File "/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ws/snake/lib/networks/dcn_v2.py", line 128, in forward
    self.deformable_groups)
  File "/home/ws/snake/lib/networks/dcn_v2.py", line 31, in forward
    ctx.deformable_groups)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:425

**Comment by wangshuo2020** [comment]
~~~
(snake_v2) ws@ws-OMEN-Laptop-15-ek0xxx:~/snake$ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.1.0'
>>> torch.version.cuda
'9.0.176'
>>> torch.backends.cudnn.version()
7501
>>> torch.cuda.is_available()
True
>>>

**Comment by wangshuo2020** [comment]
作者您好 请问可以把您实现所用到的具体软硬件环境参数列一下吗 我想完全按照您的版本来试一下

**Comment by wangshuo2020** [comment]
> 我没遇到你这个问题。
> 你说的环境应该没问题，但不确定你有没有装对。
> 你这个报错看起来好像是无法执行pytorch代码，和我的代码关系不大。

作者您好 请问可以把您实现所用到的具体软硬件环境参数列一下吗 我想完全按照您的版本来试一下

**Comment by pengsida** [comment]
你重新装驱动以后的报错看着只要重新编译代码就好了，在编译代码之前记得先把编译生成的`build`文件夹删掉。

**Comment by wangshuo2020** [comment]
> 你重新装驱动以后的报错看着只要重新编译代码就好了，在编译代码之前记得先把编译生成的`build`文件夹删掉。

谢谢您 我把环境换成了python3.6 cuda10.0 torch1.1.0 torchvision0.3.0 然后就成功了 最后运行的demo是不是用ctrl -c关不掉呢

**Comment by wangshuo2020** [comment]
直接点击图片关闭按钮也关不掉

**Comment by pengsida** [comment]
建议谷歌怎么关闭matplotib开的窗口。
